# Generated by Django 3.2.5 on 2021-07-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
